"use strict";
var __createBinding = (this && this.__createBinding) || (Object.create ? (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    var desc = Object.getOwnPropertyDescriptor(m, k);
    if (!desc || ("get" in desc ? !m.__esModule : desc.writable || desc.configurable)) {
      desc = { enumerable: true, get: function() { return m[k]; } };
    }
    Object.defineProperty(o, k2, desc);
}) : (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    o[k2] = m[k];
}));
var __setModuleDefault = (this && this.__setModuleDefault) || (Object.create ? (function(o, v) {
    Object.defineProperty(o, "default", { enumerable: true, value: v });
}) : function(o, v) {
    o["default"] = v;
});
var __importStar = (this && this.__importStar) || function (mod) {
    if (mod && mod.__esModule) return mod;
    var result = {};
    if (mod != null) for (var k in mod) if (k !== "default" && Object.prototype.hasOwnProperty.call(mod, k)) __createBinding(result, mod, k);
    __setModuleDefault(result, mod);
    return result;
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.LotteryProvider__factory = exports.IHouse__factory = exports.House__factory = exports.vendor = exports.proxySol = void 0;
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
exports.proxySol = __importStar(require("./Proxy.sol"));
exports.vendor = __importStar(require("./vendor"));
var House__factory_1 = require("./House__factory");
Object.defineProperty(exports, "House__factory", { enumerable: true, get: function () { return House__factory_1.House__factory; } });
var IHouse__factory_1 = require("./IHouse__factory");
Object.defineProperty(exports, "IHouse__factory", { enumerable: true, get: function () { return IHouse__factory_1.IHouse__factory; } });
var LotteryProvider__factory_1 = require("./LotteryProvider__factory");
Object.defineProperty(exports, "LotteryProvider__factory", { enumerable: true, get: function () { return LotteryProvider__factory_1.LotteryProvider__factory; } });
