"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.LotteryProviderProxy__factory = void 0;
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
var LotteryProviderProxy__factory_1 = require("./LotteryProviderProxy__factory");
Object.defineProperty(exports, "LotteryProviderProxy__factory", { enumerable: true, get: function () { return LotteryProviderProxy__factory_1.LotteryProviderProxy__factory; } });
